### ISSUE TITLE
Uncaught TypeError: this.config.events[e] is not a function

### ISSUE THREAD

**Issue by noone-noone** [evikza/rutube-player#1]
Привет,
я пытаюсь добавить   "events": {
   "onReady": "onPlayerReady",
    "onStateChange": "onPlayerStateChange"
  }
но получаю ошибку Uncaught TypeError: this.config.events[e] is not a function
я явно что то сделал не так, но не могу понять, что именно
заранее спасибо

**Comment by evikza** [comment]
Здравствуйте. Ошибка в документации. Вызов функций для подписи на события — без кавычек. 

```js
{
 "onReady": onPlayerReady,
 "onStateChange": onPlayerStateChange
}
